name: Promote to production when a new release is created
on:
  release:
    types:
      - created

jobs:
  promte_to_prod:
    name: Promoting ${GITHUB_REF##*/} to production
    runs-on: ubuntu-18.04
    steps:
    - name: Heroku Pipeline Promote
      uses: tiltshift/heroku-promote-app@v1
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
